# Generated by Django 5.1.2 on 2025-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('genres', models.TextField()),
                ('release_date', models.CharField(max_length=20)),
                ('overview', models.TextField()),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vote_count', models.IntegerField()),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=10)),
                ('poster_path', models.CharField(max_length=255)),
                ('video', models.BooleanField()),
                ('cast', models.TextField()),
                ('direct', models.TextField()),
                ('combined_features', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MovieVote',
                'managed': False,
            },
        ),
    ]
