# Generated by Django 5.1.2 on 2025-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_verified', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recommendations_user',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movievote',
            options={'managed': True},
        ),
    ]
